const packageSearchIndex = {
	"com.sun.jarsigner": "jdk.jartool",
	"com.sun.java.accessibility.util": "jdk.accessibility",
	"com.sun.javadoc": "jdk.javadoc",
	"com.sun.jdi": "jdk.jdi",
	"com.sun.jdi.connect": "jdk.jdi",
	"com.sun.jdi.connect.spi": "jdk.jdi",
	"com.sun.jdi.event": "jdk.jdi",
	"com.sun.jdi.request": "jdk.jdi",
	"com.sun.management": "jdk.management",
	"com.sun.net.httpserver": "jdk.httpserver",
	"com.sun.net.httpserver.spi": "jdk.httpserver",
	"com.sun.nio.sctp": "jdk.sctp",
	"com.sun.security.auth": "jdk.security.auth",
	"com.sun.security.auth.callback": "jdk.security.auth",
	"com.sun.security.auth.login": "jdk.security.auth",
	"com.sun.security.auth.module": "jdk.security.auth",
	"com.sun.security.jgss": "jdk.security.jgss",
	"com.sun.source.doctree": "jdk.compiler",
	"com.sun.source.tree": "jdk.compiler",
	"com.sun.source.util": "jdk.compiler",
	"com.sun.tools.attach": "jdk.attach",
	"com.sun.tools.attach.spi": "jdk.attach",
	"com.sun.tools.javac": "jdk.compiler",
	"com.sun.tools.javadoc": "jdk.javadoc",
	"com.sun.tools.jconsole": "jdk.jconsole",
	"java.applet": "java.desktop",
	"java.awt": "java.desktop",
	"java.awt.color": "java.desktop",
	"java.awt.datatransfer": "java.datatransfer",
	"java.awt.desktop": "java.desktop",
	"java.awt.dnd": "java.desktop",
	"java.awt.event": "java.desktop",
	"java.awt.font": "java.desktop",
	"java.awt.geom": "java.desktop",
	"java.awt.im": "java.desktop",
	"java.awt.im.spi": "java.desktop",
	"java.awt.image": "java.desktop",
	"java.awt.image.renderable": "java.desktop",
	"java.awt.print": "java.desktop",
	"java.beans": "java.desktop",
	"java.beans.beancontext": "java.desktop",
	"java.io": "java.base",
	"java.lang": "java.base",
	"java.lang.annotation": "java.base",
	"java.lang.instrument": "java.instrument",
	"java.lang.invoke": "java.base",
	"java.lang.management": "java.management",
	"java.lang.module": "java.base",
	"java.lang.ref": "java.base",
	"java.lang.reflect": "java.base",
	"java.math": "java.base",
	"java.net": "java.base",
	"java.net.http": "java.net.http",
	"java.net.spi": "java.base",
	"java.nio": "java.base",
	"java.nio.channels": "java.base",
	"java.nio.channels.spi": "java.base",
	"java.nio.charset": "java.base",
	"java.nio.charset.spi": "java.base",
	"java.nio.file": "java.base",
	"java.nio.file.attribute": "java.base",
	"java.nio.file.spi": "java.base",
	"java.rmi": "java.rmi",
	"java.rmi.activation": "java.rmi",
	"java.rmi.dgc": "java.rmi",
	"java.rmi.registry": "java.rmi",
	"java.rmi.server": "java.rmi",
	"java.security": "java.base",
	"java.security.acl": "java.base",
	"java.security.cert": "java.base",
	"java.security.interfaces": "java.base",
	"java.security.spec": "java.base",
	"java.sql": "java.sql",
	"java.text": "java.base",
	"java.text.spi": "java.base",
	"java.time": "java.base",
	"java.time.chrono": "java.base",
	"java.time.format": "java.base",
	"java.time.temporal": "java.base",
	"java.time.zone": "java.base",
	"java.util": "java.base",
	"java.util.concurrent": "java.base",
	"java.util.concurrent.atomic": "java.base",
	"java.util.concurrent.locks": "java.base",
	"java.util.function": "java.base",
	"java.util.jar": "java.base",
	"java.util.logging": "java.logging",
	"java.util.prefs": "java.prefs",
	"java.util.regex": "java.base",
	"java.util.spi": "java.base",
	"java.util.stream": "java.base",
	"java.util.zip": "java.base",
	"javax.accessibility": "java.desktop",
	"javax.annotation.processing": "java.compiler",
	"javax.crypto": "java.base",
	"javax.crypto.interfaces": "java.base",
	"javax.crypto.spec": "java.base",
	"javax.imageio": "java.desktop",
	"javax.imageio.event": "java.desktop",
	"javax.imageio.metadata": "java.desktop",
	"javax.imageio.plugins.bmp": "java.desktop",
	"javax.imageio.plugins.jpeg": "java.desktop",
	"javax.imageio.plugins.tiff": "java.desktop",
	"javax.imageio.spi": "java.desktop",
	"javax.imageio.stream": "java.desktop",
	"javax.lang.model": "java.compiler",
	"javax.lang.model.element": "java.compiler",
	"javax.lang.model.type": "java.compiler",
	"javax.lang.model.util": "java.compiler",
	"javax.management": "java.management",
	"javax.management.loading": "java.management",
	"javax.management.modelmbean": "java.management",
	"javax.management.monitor": "java.management",
	"javax.management.openmbean": "java.management",
	"javax.management.relation": "java.management",
	"javax.management.remote": "java.management",
	"javax.management.remote.rmi": "java.management.rmi",
	"javax.management.timer": "java.management",
	"javax.naming": "java.naming",
	"javax.naming.directory": "java.naming",
	"javax.naming.event": "java.naming",
	"javax.naming.ldap": "java.naming",
	"javax.naming.spi": "java.naming",
	"javax.net": "java.base",
	"javax.net.ssl": "java.base",
	"javax.print": "java.desktop",
	"javax.print.attribute": "java.desktop",
	"javax.print.attribute.standard": "java.desktop",
	"javax.print.event": "java.desktop",
	"javax.rmi.ssl": "java.rmi",
	"javax.script": "java.scripting",
	"javax.security.auth": "java.base",
	"javax.security.auth.callback": "java.base",
	"javax.security.auth.kerberos": "java.security.jgss",
	"javax.security.auth.login": "java.base",
	"javax.security.auth.spi": "java.base",
	"javax.security.auth.x500": "java.base",
	"javax.security.cert": "java.base",
	"javax.security.sasl": "java.security.sasl",
	"javax.smartcardio": "java.smartcardio",
	"javax.sound.midi": "java.desktop",
	"javax.sound.midi.spi": "java.desktop",
	"javax.sound.sampled": "java.desktop",
	"javax.sound.sampled.spi": "java.desktop",
	"javax.sql": "java.sql",
	"javax.sql.rowset": "java.sql.rowset",
	"javax.sql.rowset.serial": "java.sql.rowset",
	"javax.sql.rowset.spi": "java.sql.rowset",
	"javax.swing": "java.desktop",
	"javax.swing.border": "java.desktop",
	"javax.swing.colorchooser": "java.desktop",
	"javax.swing.event": "java.desktop",
	"javax.swing.filechooser": "java.desktop",
	"javax.swing.plaf": "java.desktop",
	"javax.swing.plaf.basic": "java.desktop",
	"javax.swing.plaf.metal": "java.desktop",
	"javax.swing.plaf.multi": "java.desktop",
	"javax.swing.plaf.nimbus": "java.desktop",
	"javax.swing.plaf.synth": "java.desktop",
	"javax.swing.table": "java.desktop",
	"javax.swing.text": "java.desktop",
	"javax.swing.text.html": "java.desktop",
	"javax.swing.text.html.parser": "java.desktop",
	"javax.swing.text.rtf": "java.desktop",
	"javax.swing.tree": "java.desktop",
	"javax.swing.undo": "java.desktop",
	"javax.tools": "java.compiler",
	"javax.transaction.xa": "java.transaction.xa",
	"javax.xml": "java.xml",
	"javax.xml.catalog": "java.xml",
	"javax.xml.crypto": "java.xml.crypto",
	"javax.xml.crypto.dom": "java.xml.crypto",
	"javax.xml.crypto.dsig": "java.xml.crypto",
	"javax.xml.crypto.dsig.dom": "java.xml.crypto",
	"javax.xml.crypto.dsig.keyinfo": "java.xml.crypto",
	"javax.xml.crypto.dsig.spec": "java.xml.crypto",
	"javax.xml.datatype": "java.xml",
	"javax.xml.namespace": "java.xml",
	"javax.xml.parsers": "java.xml",
	"javax.xml.stream": "java.xml",
	"javax.xml.stream.events": "java.xml",
	"javax.xml.stream.util": "java.xml",
	"javax.xml.transform": "java.xml",
	"javax.xml.transform.dom": "java.xml",
	"javax.xml.transform.sax": "java.xml",
	"javax.xml.transform.stax": "java.xml",
	"javax.xml.transform.stream": "java.xml",
	"javax.xml.validation": "java.xml",
	"javax.xml.xpath": "java.xml",
	"jdk.dynalink": "jdk.dynalink",
	"jdk.dynalink.beans": "jdk.dynalink",
	"jdk.dynalink.linker": "jdk.dynalink",
	"jdk.dynalink.linker.support": "jdk.dynalink",
	"jdk.dynalink.support": "jdk.dynalink",
	"jdk.javadoc.doclet": "jdk.javadoc",
	"jdk.jfr": "jdk.jfr",
	"jdk.jfr.consumer": "jdk.jfr",
	"jdk.jshell": "jdk.jshell",
	"jdk.jshell.execution": "jdk.jshell",
	"jdk.jshell.spi": "jdk.jshell",
	"jdk.jshell.tool": "jdk.jshell",
	"jdk.management.jfr": "jdk.management.jfr",
	"jdk.nashorn.api.scripting": "jdk.scripting.nashorn",
	"jdk.nashorn.api.tree": "jdk.scripting.nashorn",
	"jdk.net": "jdk.net",
	"jdk.nio": "jdk.net",
	"jdk.security.jarsigner": "jdk.jartool",
	"netscape.javascript": "jdk.jsobject",
	"org.ietf.jgss": "java.security.jgss",
	"org.w3c.dom": "java.xml",
	"org.w3c.dom.bootstrap": "java.xml",
	"org.w3c.dom.css": "jdk.xml.dom",
	"org.w3c.dom.events": "java.xml",
	"org.w3c.dom.html": "jdk.xml.dom",
	"org.w3c.dom.ls": "java.xml",
	"org.w3c.dom.ranges": "java.xml",
	"org.w3c.dom.stylesheets": "jdk.xml.dom",
	"org.w3c.dom.traversal": "java.xml",
	"org.w3c.dom.views": "java.xml",
	"org.w3c.dom.xpath": "jdk.xml.dom",
	"org.xml.sax": "java.xml",
	"org.xml.sax.ext": "java.xml",
	"org.xml.sax.helpers": "java.xml"
};

const moduleSearchIndex = new Set([
	"java.base",
	"java.compiler",
	"java.datatransfer",
	"java.desktop",
	"java.instrument",
	"java.logging",
	"java.management",
	"java.management.rmi",
	"java.naming",
	"java.net.http",
	"java.prefs",
	"java.rmi",
	"java.scripting",
	"java.se",
	"java.security.jgss",
	"java.security.sasl",
	"java.smartcardio",
	"java.sql",
	"java.sql.rowset",
	"java.transaction.xa",
	"java.xml",
	"java.xml.crypto",
	"jdk.accessibility",
	"jdk.attach",
	"jdk.charsets",
	"jdk.compiler",
	"jdk.crypto.cryptoki",
	"jdk.crypto.ec",
	"jdk.dynalink",
	"jdk.editpad",
	"jdk.hotspot.agent",
	"jdk.httpserver",
	"jdk.jartool",
	"jdk.javadoc",
	"jdk.jcmd",
	"jdk.jconsole",
	"jdk.jdeps",
	"jdk.jdi",
	"jdk.jdwp.agent",
	"jdk.jfr",
	"jdk.jlink",
	"jdk.jshell",
	"jdk.jsobject",
	"jdk.jstatd",
	"jdk.localedata",
	"jdk.management",
	"jdk.management.agent",
	"jdk.management.jfr",
	"jdk.naming.dns",
	"jdk.naming.rmi",
	"jdk.net",
	"jdk.pack",
	"jdk.rmic",
	"jdk.scripting.nashorn",
	"jdk.sctp",
	"jdk.security.auth",
	"jdk.security.jgss",
	"jdk.xml.dom",
	"jdk.zipfs"
]);

const removedPackageFromJdk11 = new Set([
	"javafx.animation",
	"javafx.application",
	"javafx.beans",
	"javafx.beans.binding",
	"javafx.beans.property",
	"javafx.beans.property.adapter",
	"javafx.beans.value",
	"javafx.collections",
	"javafx.collections.transformation",
	"javafx.concurrent",
	"javafx.css",
	"javafx.css.converter",
	"javafx.embed.swing",
	"javafx.event",
	"javafx.fxml",
	"javafx.geometry",
	"javafx.print",
	"javafx.scene",
	"javafx.scene.canvas",
	"javafx.scene.chart",
	"javafx.scene.control",
	"javafx.scene.control.cell",
	"javafx.scene.control.skin",
	"javafx.scene.effect",
	"javafx.scene.image",
	"javafx.scene.input",
	"javafx.scene.layout",
	"javafx.scene.media",
	"javafx.scene.paint",
	"javafx.scene.shape",
	"javafx.scene.text",
	"javafx.scene.transform",
	"javafx.scene.web",
	"javafx.stage",
	"javafx.util",
	"javafx.util.converter",
	"javax.activation",
	"javax.activity",
	"javax.annotation",
	"javax.jnlp",
	"javax.jws",
	"javax.jws.soap",
	"javax.rmi",
	"javax.rmi.CORBA",
	"javax.transaction",
	"javax.xml.bind",
	"javax.xml.bind.annotation",
	"javax.xml.bind.annotation.adapters",
	"javax.xml.bind.attachment",
	"javax.xml.bind.helpers",
	"javax.xml.bind.util",
	"javax.xml.soap",
	"javax.xml.ws",
	"javax.xml.ws.handler",
	"javax.xml.ws.handler.soap",
	"javax.xml.ws.http",
	"javax.xml.ws.soap",
	"javax.xml.ws.spi",
	"javax.xml.ws.spi.http",
	"javax.xml.ws.wsaddressing",
	"jdk.management.cmm",
	"jdk.management.resource",
	"jdk.packager.services",
	"jdk.packager.services.singleton",
	"org.omg.CORBA",
	"org.omg.CORBA_2_3",
	"org.omg.CORBA_2_3.portable",
	"org.omg.CORBA.DynAnyPackage",
	"org.omg.CORBA.ORBPackage",
	"org.omg.CORBA.portable",
	"org.omg.CORBA.TypeCodePackage",
	"org.omg.CosNaming",
	"org.omg.CosNaming.NamingContextExtPackage",
	"org.omg.CosNaming.NamingContextPackage",
	"org.omg.Dynamic",
	"org.omg.DynamicAny",
	"org.omg.DynamicAny.DynAnyFactoryPackage",
	"org.omg.DynamicAny.DynAnyPackage",
	"org.omg.IOP",
	"org.omg.IOP.CodecFactoryPackage",
	"org.omg.IOP.CodecPackage",
	"org.omg.Messaging",
	"org.omg.PortableInterceptor",
	"org.omg.PortableInterceptor.ORBInitInfoPackage",
	"org.omg.PortableServer",
	"org.omg.PortableServer.CurrentPackage",
	"org.omg.PortableServer.POAManagerPackage",
	"org.omg.PortableServer.POAPackage",
	"org.omg.PortableServer.portable",
	"org.omg.PortableServer.ServantLocatorPackage",
	"org.omg.SendingContext",
	"org.omg.stub.java.rmi"
  ]);